title: Ignacio Gómez
description: >- # this means to ignore newlines until "baseurl:"
  iOS Software Engineer & Triathlete
author:
  name: Ignacio Gómez
  email: igomez@relative.cl
#url: 'https://xrelative.github.io'
#baseurl: "/" # the subpath of your site, e.g. /blog
#root: '/'
google_analytics: 'UA-44707583-1'

# Social accounts
social:
  twitter_username: xrelative
  github_username:  xrelative
  linkedin_username: gomezignacio
  medium_username: relative
  stackoverflow_username: ignacio-gómez
  stackoverflow_id: 1746482
  instagram_username: xrelative
  wordpress_username: xrelative

# Build settings
theme: jekyll-theme-minimal
