# Site settings
title: 'Ignacio Gómez'
description: 'iOS Developer, ourdoor lover and geek'
url: 'https://xrelative.github.io'
baseurl: '/'
root: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ignacio Gómez'
  email: igomez@relative.cl
  twitter_username: xrelative
  facebook_username: xrelative
  github_username: xrelative
  linkedin_username: gomezignacio

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
